assn3: main.cpp Group.o Member.o Vote.o
	g++ -Iinclude/ -o assn3 main.cpp Group.o Member.o Vote.o

Group.o: Group.h Group.cpp
	g++ -Iinclude/ -c -o Group.o Group.cpp

Vote.o: Vote.h Vote.cpp
	g++ -Iinclude/ -c -o Vote.o Vote.cpp

Member.o: member.h Member.cpp
	g++ -Iinclude/ -c -o Member.o Member.cpp
